<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <link rel="shortcut icon" href="/images/icons/favicon.ico" mce_href="favicon.ico">
    <title>API &middot; NACOSS National</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="apple-touch-icon" sizes="180x180" href="/images/icons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/images/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/icons/favicon-16x16.png">
    <link rel="manifest" href="/images/icons/site.webmanifest">
    <link rel="mask-icon" href="/images/icons/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
            text-align: center;
            color: #aaa;
            font-size: 18px;
            background: white;
            text-align: center;
        }

        .logo {
            width: 40%;
            margin: auto;
            margin-top: 50px;
            padding-top: 20px;
        }

        h3 {
            font-size: 3.0em;
            font-weight: 100;
            letter-spacing: 0.7em;
            text-transform: uppercase;
            text-shadow: 0px 0px 20px #6EC3EC;
            color: #000000;
            margin-top: 20px;
            padding-top: 20px;
            margin-top: 10px;
        }
    </style>
</head>

<body>
    <img class="logo" src="/images/logo.png" />
    <h3>API Services</h3>
    <p style="margin-top:5%;">Built with  by</p>
    <p>
        <a href="//www.linkedin.com/in/itssadon" target="_black">
            <img src="//instagram.flos1-1.fna.fbcdn.net/vp/fef4b781e76795985b2d29eff9ab3e01/5B975CE3/t51.2885-19/s150x150/19985260_455577861486597_8259592877554794496_a.jpg" width="132px" style="border-radius: 50%;" />
        </a>
    </p>
</body>

</html>